"""empty message

Revision ID: 842a450d2a6a
Revises: dfd5b2d3552f
Create Date: 2026-03-17 10:01:41.235993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '842a450d2a6a'
down_revision = 'dfd5b2d3552f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
